# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI (Maven & Gradle)

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest

        # Runs both Maven and Gradle builds to keep both build scripts healthy
        strategy:
            matrix:
                build-tool: [maven, gradle]

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: ${{ matrix.build-tool }}

            - name: Build with Maven
              if: matrix.build-tool == 'maven'
              run: mvn -B package --file pom.xml

            - name: Build with Gradle
              if: matrix.build-tool == 'gradle'
              run: ./gradlew --no-daemon clean build
